config/routes.rb
Rails.application.routes.draw do
  post 'logins/create'

  get "login" => "logins#new", :as => "login"
  get "logout" => "logins#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
 
  resources :forums

  resources :projects do
       resources :tasks
  end

  resources :users

   root 'projects#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :Project
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    if session[:user_id] != 1
      redirect_to "404.html"
    end
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show    
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.project_id = params[:project_id]

    @combo = User.all
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find_by_id(params[:id])
    @user = User.find_by_id(session[:user_id])
    if @user.email != @task.user_email && @user.id != 1
      redirect_to "404.html"
    end
    @combo = User.all
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @project = Project.find(@task.project_id)

    respond_to do |format|
      if @task.save
        format.html { redirect_to [@project, @task], notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @project = Project.find(@task.project_id)
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to [@project, @task], notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project = Project.find(@task.project_id)
    @task.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:nome, :description, :dateStart, :dateEnd, :stats, :project_id, :user_email)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task, url: :project_tasks ) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :dateStart %><br>
    <%= f.date_select :dateStart, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :dateEnd %><br>
    <%= f.date_select :dateEnd, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :stats %><br>
    <%= f.text_field :stats, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id, :readonly => true, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :user_email %>
    <%= f.select :user_email, options_for_select(@combo.map{|u| [u.email, u.email]}, :selected => @task.user_email), 
    {}, {:class => "form-control"} %>
  </div>
   <!-- <div class="field">
    < %= f.label :user_email %><br>
    < %= f.text_field :user_email, :class => "form-control" %>
  </div>-->
  <br>
  <div class="actions">
    <%= f.submit "Criar Tarefa", class: "btn btn-primary btn-sm" %>
  </div>
  <br>
<% end %>

app/views/tasks/_form_edit.html.erb
<%= form_for(@task, url: :project_task ) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :dateStart %><br>
    <%= f.date_select :dateStart, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :dateEnd %><br>
    <%= f.date_select :dateEnd, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :stats %><br>
    <%= f.text_field :stats, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id, :readonly => true, :class => "form-control" %>
  </div>
   <div class="field">
    <%= f.label :user_email %><br>
    <%= f.text_field :user_email, :class => "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Salvar Alterações",class: "btn btn-primary btn-sm" %>
  </div>
  <br>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editar Tarefa</h1>

<%= render 'form_edit' %>

<%= link_to 'Vizualizar', project_task_path(@task.project_id, @task), class: "btn btn-default btn-sm" %> |
<%= link_to 'Voltar', projects_path(@project), class: "btn btn-default btn-sm" %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Description</th>
      <th>Datestart</th>
      <th>Dateend</th>
      <th>Stats</th>
      <th>Projectid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.nome %></td>
        <td><%= task.description %></td>
        <td><%= task.dateStart %></td>
        <td><%= task.dateEnd %></td>
        <td><%= task.stats %></td>
        <td><%= task.project_id %></td>
        <td><%= link_to 'Show', project_task_path(task.project_id, task), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_project_task_path(task.project_id, task), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Destroy', project_task_path(task.project_id, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_path, class: "btn btn-default btn-sm" %>

app/views/tasks/new.html.erb
<h1>Nova Tarefa</h1>

<%= render 'form' %>

<%= link_to 'Voltar', projects_path(@project), class: "btn btn-default btn-sm" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Tarefa</h1>
<p>
  <strong>Nome:</strong>
  <%= @task.nome %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Data de Inicio:</strong>
  <%= @task.dateStart %>
</p>

<p>
  <strong>Data de Finalização:</strong>
  <%= @task.dateEnd %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.stats %>
</p>

<p>
  <strong>Projectid:</strong>
  <%= @task.project_id %>
</p>

<p>
  <strong>Usuário:</strong>
  <%= @task.user_email %>
</p>

<%= link_to 'Voltar', project_path(@task.project_id), class: "btn btn-default btn-sm" %>