config/routes.rb
Rails.application.routes.draw do
  post 'logins/create'

  get "login" => "logins#new", :as => "login"
  get "logout" => "logins#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
 
  resources :forums

  resources :projects do
       resources :tasks
  end

  resources :users

   root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	has_many :forums
	belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  # GET /projects
  # GET /projects.json
  def index
  #  @user = User.find_by_id(session[:user_id])
  #  @projects = @user.projects
  #  @projects = Project.find_by_user_id(session[:user_id])

    @projects = Project.where(:user_id => session[:user_id])


    @user = User.find_by_id(session[:user_id])
    @tasks = Task.where(:user_email => @user.email)
    @tasks.order(dateEnd: :asc)
    @projectsPart = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @forum = Forum.new
    @forum.project_id = @project.id
    @user = User.find_by_id(session[:user_id])
    @forum.user_id = @user.id
    @forum.name_user = @user.nome
  end

  # GET /projects/new
  def new

    @project = Project.new
    @user = User.find_by_id(session[:user_id])
    @project.user_id = @user.id
@u = User.all
  end

  # GET /projects/1/edit
  def edit
    @user = User.find_by_id(session[:user_id])
    @project = Project.find_by_id(params[:id])
    if @user.id != 1 && @user.id != @project.user_id
      redirect_to "404.html"
    end
    @u = User.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
       # @project.user_id = session[:current_user_id]
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:nome, :description, :date, :user_id, :stats)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Descrição" %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Data" %><br>
    <%= f.date_select :date, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, :readonly => true, :class => "form-control" %>
  </div>
  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.select :user_id, options_for_select(@u.map{|u| [u.email, u.id]}, :selected => @project.user_id), 
    {}, {:class => "form-control"} %>
  </div>-->
  <div class="field">
    <%= f.label "Status" %><br>
    <%= f.text_field :stats, :class => "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Salvar",class: "btn btn-primary btn-sm" %>
  </div>
  <br>
<% end %>

app/views/projects/edit.html.erb
<h1>Editar Projeto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', projects_path, class: "btn btn-default btn-sm" %>

app/views/projects/index.html.erb
<h1>Meus Projetos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Data</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.nome %></td>
        <td><%= project.description %></td>
        <td><%= project.date %></td>
        <td><%= project.stats %></td>
        <td><%= link_to 'Exibir', project, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Editar', edit_project_path(project), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Excluir', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Projeto', new_project_path, class: "btn btn-primary btn-sm" %>

<hr>

<h2>Minhas Tarefas</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Tarefa</th>
      <th>Projeto</th>
      <th>Data de Inicio</th>
      <th>Data de Finalização</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projectsPart.each do |proj| %>
    <% @tasks.each do |task| %>
    
    <% if task.project_id == proj.id %>

      <tr>
        <td><%= task.nome %></td>
        <td><%= proj.nome %></td>
        <td><%= task.dateStart %></td>
        <td><%= task.dateEnd %></td>
        <td><%= task.stats %></td>        
        <td><%= link_to 'Visualizar', proj, class: "btn btn-default btn-sm" %></td>
      </tr>
      <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>Novo Projeto</h1>

<%= render 'form' %>

<%= link_to 'Sair', projects_path, class: "btn btn-default btn-sm" %>

app/views/projects/show.html.erb
<p id="notice" class="bg-success"><%= notice %></p>

<h1>Projeto</h1>
<p>
  <strong>Nome:</strong>
  <%= @project.nome %>
</p>

<p>
  <strong>Data:</strong>
  <%= @project.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.stats %>
</p>


<p>
  <strong>Descrição:</strong>
  <%= @project.description %>
</p>

<hr>
<p>

 <h1>Tarefas</h1> 
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data de Inicio</th>
      <th>Data de Finalização</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project.tasks.each do |task| %>
      <tr>
        <td><%= task.nome %></td>
        <td><%= task.dateStart %></td>
        <td><%= task.dateEnd %></td>
        <td><%= task.stats %></td>

        

        <td><%= link_to 'Visualizar', project_task_path(task.project_id, task), class: "btn btn-default btn-sm" %></td>

        
        <td>
          <% if task.user_email == @user.email || @user.id == @project.user_id %>
          <%= link_to 'Editar', edit_project_task_path(task.project_id, task), class: "btn btn-default btn-sm" %>
          <%end %>
        </td>

        <% if @user.id == @project.user_id || @user_id == 1%>
        <td><%= link_to 'Excluir', project_task_path(task.project_id, task), class: "btn btn-default btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
         
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</p>


<% if @project.user_id == @user.id %>  <!-- testa usuario - arrumar aqui -->

<%= link_to 'Nova Tarefa', new_project_task_path(@project), class: "btn btn-primary btn-sm" %>
<% end %>
<div >
<hr>

<p>
  <%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<h2>Escrever Mensagem</h2> 
<div class="container">
  <div class="row">
    <div class="col-sm-8 contact-form">
      <form id="contact" method="post" class="form" role="form">
        <div class="row">
          <div class="col-xs-6 col-md-6 form-group">
            <td><%= f.label 'Nome:' %></td>
            <%= f.text_field :name_user,:readonly => true, :class => "form-control" %>
          </div>
          <div class="col-xs-3 col-md-3 form-group">
            <td><%= f.label 'Id do Projeto:' %></td>
            <%= f.number_field :project_id,:readonly => true, :class => "form-control" %>
          </div>
          <div class="col-xs-3 col-md-3 form-group">
            <td><%= f.label 'Id de Usuário:' %></td>
            <%= f.number_field :user_id,:readonly => true, :class => "form-control" %>
          </div>
      </div>
      <%= f.text_area :message, :class => "form-control", :placeholder => "Message", :rows => "5" %>
      <br/>
      <%= f.date_select :data, :readonly => true, :class => "form-control" %>
      <div class="row">
       <div class="col-xs-12 col-md-12 form-group">
        <div class="actions">
          <%= submit_tag "Enviar", :class => "btn btn-primary pull-right", :type => "submit" %>
        </div>
     </form>
  </div>
</div>

<% end %>
<hr>
  <h2>Mensagens</h2>
  <br />
    <% @project.forums.each do |msg| %>
      <p>
        <strong><%= msg.name_user + " (" + @user.email + ")" %> </strong> (<%= msg.data %>): <br><%= msg.message %>
      </p>
      </br>
    <% end %>

</div>