config/routes.rb
Rails.application.routes.draw do
  post 'logins/create'

  get "login" => "logins#new", :as => "login"
  get "logout" => "logins#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
 
  resources :forums

  resources :projects do
       resources :tasks
  end

  resources :users

   root 'projects#index'

end

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
 <%= link_to "Syspro", root_path, :class=> 'navbar-brand' %>
</div>
<ul class="nav navbar-nav">
  <% if session[:user_id] != nil %>
  <li>
    <%= link_to "Projetos", projects_path %>
  </li>
  <% if session[:user_id] == 1%>
  <li>
    <%= link_to "Usuários", users_path %>
  </li>
  <% end %>
  
  <li>
    <%= link_to "Meu Perfil", edit_user_path(session[:user_id]) %>
  </li>
  <%end %>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li>
  	<% if session[:user_id] %>
  <%= link_to 'Logout', logout_path %>
 	<% end %>
  </li>
</ul>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syspro</title>
  <%= stylesheet_link_tag    "bootswatch.min", :media => "all" %>
  <%= javascript_include_tag "jquery-1.11.1.min" %>
  <%= javascript_include_tag "bootstrap.min" %>
 <!--< %= javascript_include_tag "application" %> -->

</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top">    
  <div class="container">
      <%= render 'layouts/navigation' %>
  </div>
  </div>



<div class="container" style="margin-top:60px">
 <%= yield %>
</div>
  <div class="container" style="padding-top:60px">
    <hr>
    <p class="text-muted credit">© SysPro 2015</p>
  </div>

</body>
</html>